#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Oct 07 18:00:28 -03 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto c5e0958d6a8e4f3ea91c86a6fff04ecf --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot clock_sim_behav xil_defaultlib.clock_sim -log elaborate.log"
xelab -wto c5e0958d6a8e4f3ea91c86a6fff04ecf --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot clock_sim_behav xil_defaultlib.clock_sim -log elaborate.log

